//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicUniversityStationeryStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.DisbursementLists = new HashSet<DisbursementList>();
            this.Employees = new HashSet<Employee>();
            this.Requests = new HashSet<Request>();
        }
    
        public string name { get; set; }
        public string code { get; set; }
        public string deptHead { get; set; }
        public string deptRep { get; set; }
        public string contactName { get; set; }
        public string telNo { get; set; }
        public string faxNo { get; set; }
        public string collectionPt { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual ICollection<DisbursementList> DisbursementLists { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
    }
}
