//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicUniversityStationeryStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Departments = new HashSet<Department>();
            this.Departments1 = new HashSet<Department>();
            this.DisbursementLists = new HashSet<DisbursementList>();
            this.GCMs = new HashSet<GCM>();
            this.PurchaseOrders = new HashSet<PurchaseOrder>();
            this.Requests = new HashSet<Request>();
            this.StockAdjustments = new HashSet<StockAdjustment>();
            this.StockAdjustments1 = new HashSet<StockAdjustment>();
        }
    
        public string empNo { get; set; }
        public string empName { get; set; }
        public string empPassword { get; set; }
        public string deptCode { get; set; }
        public string telNo { get; set; }
        public string email { get; set; }
        public string empRole { get; set; }
        public string designation { get; set; }
        public Nullable<System.DateTime> authorizeStart { get; set; }
        public Nullable<System.DateTime> authorizeEnd { get; set; }
    
        public virtual ICollection<Department> Departments { get; set; }
        public virtual ICollection<Department> Departments1 { get; set; }
        public virtual Department Department { get; set; }
        public virtual ICollection<DisbursementList> DisbursementLists { get; set; }
        public virtual ICollection<GCM> GCMs { get; set; }
        public virtual ICollection<PurchaseOrder> PurchaseOrders { get; set; }
        public virtual ICollection<Request> Requests { get; set; }
        public virtual ICollection<StockAdjustment> StockAdjustments { get; set; }
        public virtual ICollection<StockAdjustment> StockAdjustments1 { get; set; }
    }
}
