//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicUniversityStationeryStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrderDetail
    {
        public int id { get; set; }
        public int orderID { get; set; }
        public string stationeryCode { get; set; }
        public int requestedQuantity { get; set; }
        public Nullable<int> receivedQuantity { get; set; }
        public decimal amount { get; set; }
    
        public virtual PurchaseOrder PurchaseOrder { get; set; }
        public virtual Stationery Stationery { get; set; }
    }
}
