//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicUniversityStationeryStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestByDept
    {
        public int id { get; set; }
        public string stationeryCode { get; set; }
        public int deliveryID { get; set; }
        public int neededQuantity { get; set; }
        public Nullable<int> retrievedQuantity { get; set; }
        public Nullable<int> disbursedQuantity { get; set; }
    
        public virtual DisbursementList DisbursementList { get; set; }
        public virtual Stationery Stationery { get; set; }
    }
}
