//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicUniversityStationeryStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public Request()
        {
            this.RequestDetails = new HashSet<RequestDetail>();
        }
    
        public int id { get; set; }
        public Nullable<System.DateTime> dateOfApp { get; set; }
        public string deptCode { get; set; }
        public string empNo { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> lastUpdate { get; set; }
        public Nullable<int> deliveryID { get; set; }
        public string rejectedReason { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual DisbursementList DisbursementList { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<RequestDetail> RequestDetails { get; set; }
    }
}
