//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicUniversityStationeryStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stationery
    {
        public Stationery()
        {
            this.PurchaseOrderDetails = new HashSet<PurchaseOrderDetail>();
            this.RequestByDepts = new HashSet<RequestByDept>();
            this.RequestDetails = new HashSet<RequestDetail>();
            this.StockAdjustmentDetails = new HashSet<StockAdjustmentDetail>();
        }
    
        public string code { get; set; }
        public string category { get; set; }
        public string description { get; set; }
        public string unitOfMeasure { get; set; }
        public string reorderLevel { get; set; }
        public string reorderQuantity { get; set; }
        public Nullable<decimal> price1 { get; set; }
        public Nullable<decimal> price2 { get; set; }
        public Nullable<decimal> price3 { get; set; }
        public string supplier1 { get; set; }
        public string supplier2 { get; set; }
        public string supplier3 { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual ICollection<PurchaseOrderDetail> PurchaseOrderDetails { get; set; }
        public virtual ICollection<RequestByDept> RequestByDepts { get; set; }
        public virtual ICollection<RequestDetail> RequestDetails { get; set; }
        public virtual Supplier Supplier { get; set; }
        public virtual Supplier Supplier4 { get; set; }
        public virtual Supplier Supplier5 { get; set; }
        public virtual ICollection<StockAdjustmentDetail> StockAdjustmentDetails { get; set; }
    }
}
