//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicUniversityStationeryStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAdjustmentDetail
    {
        public int id { get; set; }
        public int reportID { get; set; }
        public string stationeryCode { get; set; }
        public decimal amount { get; set; }
        public string reason { get; set; }
        public int quantity { get; set; }
    
        public virtual Stationery Stationery { get; set; }
        public virtual StockAdjustment StockAdjustment { get; set; }
    }
}
