//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicUniversityStationeryStore
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockAdjustment
    {
        public StockAdjustment()
        {
            this.StockAdjustmentDetails = new HashSet<StockAdjustmentDetail>();
        }
    
        public int id { get; set; }
        public string status { get; set; }
        public string submittedBy { get; set; }
        public string reviewedBy { get; set; }
        public Nullable<System.DateTime> reviewDate { get; set; }
        public string reviewReason { get; set; }
        public string showTo { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual ICollection<StockAdjustmentDetail> StockAdjustmentDetails { get; set; }
    }
}
